# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#

#
# Site configuration
#

title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # does not include hostname / the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username:  jekyll

#
# Release configuration
#
# Documentation: http://docs.cloudcannon.com/hosting/environments/

development:
  asset_url: "http://localhost:1337/"
  app_url: "http://localhost:3000/"

staging:
  asset_url: "https://staging.example.org/assets/"
  app_url: "https://staging.example.org/"

production:
  asset_url: "https://cdn.example.org/"
  app_url: "https://app.example.org/"

#
# Build configuration
#
# Documentation: http://jekyllrb.com/docs/configuration/#default-configuration

# Where things are
collections:
  - portfolio

# Handling Reading
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpfile.js"
  - "package.json"
  - "README.md"

# Conversion
markdown: kramdown
