# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#
# Site configuration
#

title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  
baseurl: "" # does not include hostname / the subpath of your site, e.g. /blog 
url: "http://yourdomain.com" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username:  jekyll


#
# Build configuration
#
# Documentation: http://jekyllrb.com/docs/configuration/

# Where things are
source:       #./src
destination:  #./src/_site
plugins_dir:  ./src/_plugins
layouts_dir:  ./src/_layouts
data_dir:     ./src/_data
includes_dir: ./src/_includes
# collections:  null

# Conversion
markdown:    kramdown
# highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach:  false
port:    9001
host:    0.0.0.0
## baseurl: defined in site configuration ##

# Outputting
permalink:     pretty
paginate_path: /page:num
timezone:      null